name: Publish erdjs-snippets

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      # - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo " - [npmjs](https://www.npmjs.com/package/@elrondnetwork/erdjs-snippets)" >> notes.txt
          echo "" >> notes.txt

          RELEASE_TAG=v$(node -p "require('./package.json').version")
          gh release create $RELEASE_TAG --prerelease --title="$RELEASE_TAG" --generate-notes --notes-file=notes.txt
